-- 1. CUSTOMER Table
CREATE TABLE CUSTOMER (
    Patient_ID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Contact_No VARCHAR(15) NOT NULL
);
-- 2. DRUG_MANUFACTURER Table
CREATE TABLE DRUG_MANUFACTURER (
    Company_ID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
); 
-- 3. DOCTOR Table
CREATE TABLE DOCTOR (
Doctor_ID INT PRIMARY KEY,
    Contact_No VARCHAR(15) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Specialization VARCHAR(255) NOT NULL
); 
-- 4. DISTRIBUTOR Table
CREATE TABLE DISTRIBUTOR (
    Distributor_ID INT PRIMARY KEY,
    Contact_No VARCHAR(15) NOT NULL
);
-- 5. EMPLOYEE Table
CREATE TABLE EMPLOYEE (
    Employee_ID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Contact_No VARCHAR(15) NOT NULL
);
-- 6. PURCHASE Table
CREATE TABLE PURCHASE (
    Purchase_ID INT PRIMARY KEY,
    Date DATE NOT NULL
);
-- 7. SALE_TRANSACTION Table
CREATE TABLE SALE_TRANSACTION (
    Sale_ID INT NOT NULL,
    Date DATE NOT NULL,
    Employee_ID INT NOT NULL,
    PRIMARY KEY (Sale_ID, Employee_ID),
    FOREIGN KEY (Employee_ID) REFERENCES EMPLOYEE(Employee_ID)
);


-- 8. SELLS Table
CREATE TABLE SELLS (
    Sale_ID INT NOT NULL,
    Drug_ID INT NOT NULL,
    Patient_ID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    PRIMARY KEY (Sale_ID, Drug_ID, Patient_ID),
    FOREIGN KEY (Sale_ID) REFERENCES SALE_TRANSACTION(Sale_ID),
    FOREIGN KEY (Drug_ID) REFERENCES DRUG(Drug_ID),
    FOREIGN KEY (Patient_ID) REFERENCES CUSTOMER(Patient_ID)
);

-- 9. PRESCRIBES Table
CREATE TABLE PRESCRIBES (
    Patient_ID INT NOT NULL,
    Doctor_ID INT NOT NULL,
    Drug_ID INT NOT NULL,
    PRIMARY KEY (Patient_ID, Doctor_ID, Drug_ID),
    FOREIGN KEY (Patient_ID) REFERENCES CUSTOMER(Patient_ID),
    FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID),
    FOREIGN KEY (Drug_ID) REFERENCES DRUG(Drug_ID)
);

-- 10. DRUG Table
CREATE TABLE DRUG (
    Drug_ID INT PRIMARY KEY,
    Location VARCHAR(255) NOT NULL,
    Cost_Price DECIMAL(10, 2) NOT NULL,
    Stock INT NOT NULL CHECK (Stock >= 0),
    Name VARCHAR(255) NOT NULL,
    Discount DECIMAL(5, 2) NOT NULL,
    MRP DECIMAL(10, 2) NOT NULL,
    Company_ID INT NOT NULL,
    Expiry DATE NOT NULL,
    FOREIGN KEY (Company_ID) REFERENCES DRUG_MANUFACTURER(Company_ID)
);
-- 11. SUPPLIES Table
CREATE TABLE SUPPLIES (
    Quantity INT NOT NULL CHECK (Quantity > 0),
    Purchase_ID INT NOT NULL,
    Distributor_ID INT NOT NULL,
    Drug_ID INT NOT NULL,
    PRIMARY KEY (Distributor_ID, Drug_ID, Purchase_ID),
    FOREIGN KEY (Purchase_ID) REFERENCES PURCHASE(Purchase_ID),
    FOREIGN KEY (Distributor_ID) REFERENCES DISTRIBUTOR(Distributor_ID),
    FOREIGN KEY (Drug_ID) REFERENCES DRUG(Drug_ID)
);

